name: FindMyEntities
version: 1.0.1-SNAPSHOT
main: coffee.suddenly.findmyentities.Main
author: Suddenly
description: Find the chunks causing your entity issues
website: www.suddenly.coffee
commands:
    findmyentities:
        description: Find all the (tile)entities in the player's current world or specified world
        usage: /<command> <tileeneitites/entities> (world) (radius in chunks from 0,0)
        permission: findmyentities.find
    teleporttochunk:
        description: Teleports you to the corner of a specified chunk
        usage: /<command> <int> <int> (world)
        permission: findmyentities.teleport